Description of loadStandardModeConfig
Home > Imaging > io > scanFieldControl > loadStandardModeConfig.m
loadStandardModeConfig
PURPOSE
SYNOPSIS
function loadStandardModeConfig()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
initGUIs opens and interprets and initialization file
updateChannelFlags
updateDataForConfiguration
This function is called by:
SOURCE CODE
function loadStandardModeConfig()
    global state;
    out=0;
    configSelected=1;
    if isnumeric(state.configName) | length(state.configName)==0
        configSelected=0;
    else
        [flag, fname, pname, ext]=initGUIs([state.configPath '\' state.configName '.cfg'], 0);
        if flag==0
            configSelected=0;
        end
    end
    if configSelected
        setStatusString('Config read in...');
        state.configName=fname;
        state.configPath=pname;
    else
        setStatusString('Using config in memory');
        disp('loadStandardModeConfig: No configuration selected.  Using parameters currently in memory');
        state.configName='Default';
        state.configPath='';
    end
    updateChannelFlags;
    updateDataForConfiguration;
    state.internal.configurationChanged=0;
    setStatusString('');