Description of parkMirrors
Home > Imaging > io > scanFieldControl > parkMirrors.m
parkMirrors
PURPOSE
SYNOPSIS
function parkMirrors(xy)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
endAcquisition
initImaging
pcellTest
SOURCE CODE
function parkMirrors(xy)
    global state
    if nargin~=1
        putsample(state.daq.parkMirrorsOutput, [state.acq.scanOffsetX ...
                state.acq.scanOffsetY])
    else
        if length(xy)~=2
            error('parkMirrors: expected [x y] as input');
        else
            putsample(state.daq.parkMirrorsOutput, xy);    % Queues Data to engine for Board 2 (Mirrors)
        end
    end