Description of stopAndRestartFocus
Home > Imaging > io > scanFieldControl > stopAndRestartFocus.m
stopAndRestartFocus
PURPOSE
SYNOPSIS
function stopAndRestartFocus
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
startFocus
flushFocusData
putDataFocus
setPcellsToDefault
This function is called by:
makeStripe makeStripe.m*****
SOURCE CODE
function stopAndRestartFocus
    global state
    state.internal.pauseAndRotate=0;
    global focusInput focusOutput pcellFocusOutput
    deviceList=[focusInput focusOutput];
    if state.pcell.pcellOn
        deviceList(end+1)=pcellFocusOutput;
    end
    stop(deviceList);
    while ~any(strcmp(get(deviceList, 'Running'), 'Off'))
        pause(0.01);
    end
    setPcellsToDefault
    flushFocusData;
    if get(focusInput, 'SamplesAvailable')>0
        try
            flushdata(focusInput);
        catch
            disp(lasterr);
        end
    end
    putDataFocus;
    state.internal.stripeCounter=0;
    state.internal.frameCounter = 0;
    updateGUIByGlobal('state.internal.frameCounter');
    startFocus;