Description of updateCycleDisplay
Home > Imaging > io > scanFieldControl > updateCycleDisplay.m
updateCycleDisplay
PURPOSE
SYNOPSIS
function updateCycleDisplay(position)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
timerCallPackageFunctions
This function is called by:
advancedCycleGUI ADVANCEDCYCLEGUI M-file for advancedCycleGUI.fig
TNDefCycle
TNDefCycleSlow
TNDefCycleTrackerOnly
deleteCyclePosition
initTimer
insertCyclePosition
loadCycle
SOURCE CODE
function updateCycleDisplay(position)
    global state
    createPosition=0;
    if nargin<1
        position=state.cycle.displayCyclePosition;
    else
        if position>length(state.cycle.delayList)
            position=length(state.cycle.delayList)+1;
            createPosition=1;
        end
        state.cycle.displayCyclePosition=position;
        updateGUIByGlobal('state.cycle.displayCyclePosition');
    end
    for counter=1:length(state.internal.cycleListNames)
        if createPosition
            if strcmp(state.internal.cycleListNames{counter}, 'frames')
                state.cycle.framesList(state.cycle.displayCyclePosition)=1;
            elseif strcmp(state.internal.cycleListNames{counter}, 'delay')
                state.cycle.delayList(state.cycle.displayCyclePosition)=10;
            elseif strcmp(state.internal.cycleListNames{counter}, 'repeats')
                state.cycle.repeatsList(state.cycle.displayCyclePosition)=1;
            elseif strcmp(state.internal.cycleListNames{counter}, 'zStepSize')
                state.cycle.zStepSizeList(state.cycle.displayCyclePosition)=1;
            elseif strcmp(state.internal.cycleListNames{counter}, 'numberOfZSlices')
                state.cycle.numberOfZSlicesList(state.cycle.displayCyclePosition)=1;
            elseif strcmp(state.internal.cycleListNames{counter}, 'functionName')
                state.cycle.functionNameList{state.cycle.displayCyclePosition}='';
            else
                eval(['state.cycle.' state.internal.cycleListNames{counter} 'List(state.cycle.displayCyclePosition) = 0;']);
            end
        end
        if isnumeric(getfield(state.cycle, state.internal.cycleListNames{counter}))
            eval(['state.cycle.' state.internal.cycleListNames{counter} '=state.cycle.' state.internal.cycleListNames{counter} 'List(state.cycle.displayCyclePosition);']);
        else
            eval(['state.cycle.' state.internal.cycleListNames{counter} '=state.cycle.' state.internal.cycleListNames{counter} 'List{state.cycle.displayCyclePosition};']);
        end
        updateGUIByGlobal(['state.cycle.' state.internal.cycleListNames{counter}]);
    end
    timerCallPackageFunctions('CycleChanged');