Description of saveCycleAs
Home > Timer > saveCycleAs.m
saveCycleAs
PURPOSE
save pulse set to disk with new name
SYNOPSIS
function saveCycleAs
DESCRIPTION
 save pulse set to disk with new name
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
saveCycle writes pulseSet to disk
This function is called by:
saveCycle writes pulseSet to disk
SOURCE CODE
function saveCycleAs
% save pulse set to disk with new name
    global state
    if ~isempty(state.cycle.cyclePath)
        try
            cd(state.cycle.cyclePath)
        catch
        end
    end
    [fname, pname]=uiputfile('*.cyc', 'Choose file for cycle');
    if ~isnumeric(fname)
        periods=findstr(fname, '.');
        if any(periods)
            fname=fname(1:periods(1)-1);
        end
        fname=[fname '.cyc'];
        state.cycle.cycleName = fname;
        state.cycle.cyclePath = pname;
        updateGUIByGlobal('state.cycle.cycleName');
        saveCycle;
        makeCycleMenu;
        checkCurrentCycleInMenu;
    else
        setStatusString('Cannot open file');
    end