Description of saveAnalysisSetup
Home > Timer > saveAnalysisSetup.m
saveAnalysisSetup
PURPOSE
SYNOPSIS
function saveAnalsysSetup
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
saveAnalysisSetupAs
This function is called by:
saveAnalysisSetupAs
SOURCE CODE
function saveAnalsysSetup
    global state
    setStatusString('saving analysis setup...');
    varList={...
            'active' ...
            'setup' ...
            'analysisMode' ...
            'numberOfROI' ...
            'autosetROI' ...
            'avgLineScanStart' ...
            'avgLineScanEnd' ...
            'avgLineScanSmooth' ...
            'avgLineScanChannel' ...
            'flBaseLineStart' ...
            'flBaseLineEnd' ...
            'roiWidth' ...
            'anaChannel1' ...
            'anaChannel2' ...
            'anaChannel3' ...
            'anaChannel4' ...
            'autosubOffset1' ...
            'autosubOffset2' ...
            'autosubOffset3' ...
            'autosubOffset4' ...
            'plot1' ...
            'plot2' ...
            'plot3' ...
            'plot4' ...
            'ratioMode1' ...
            'ratioMode2' ...
            'ratioMode3' ...
            'ratioMode4' ...
            };
    if isempty(state.analysis.setupPath) | isempty(state.analysis.setupName)
        saveAnalysisSetupAs;
    else
        for counter=1:length(varList);
            eval(['analysis.' varList{counter} ' = state.analysis.' varList{counter} ';']);
        end
        save(fullfile(state.analysis.setupPath, state.analysis.setupName), 'analysis', '-MAT');
        setStatusString('analysis setup saved');
    end