Description of timerLoop
Home > Timer > timerLoop.m
timerLoop
PURPOSE
SYNOPSIS
function timerLoop
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
hideGUI
setStatusString This function sets the status field in mainControls.
savingInfoIsOK updated by tp 10/25/01
timerCallPackageFunctions
timerGetActiveStatus
timerMainLoop
timerPausedStatus
This function is called by:
timerMainControls TIMERMAINCONTROLS M-file for timerMainControls.fig
SOURCE CODE
function timerLoop
    global state gh
    val=get(gh.timerMainControls.loop, 'String');
    if strcmp(val, 'LOOP')
        if timerPausedStatus
            beep;
            setStatusString('Running. Stop processes');
            return
        end
        if ~savingInfoIsOK(~timerGetActiveStatus('Imaging'))
            return
        end
        setStatusString('Starting loop...');
        state.internal.firstTimeThroughLoop=1;
        set(gh.timerMainControls.loop, 'String', 'ABORT');
        hideGUI('gh.timerMainControls.doOne');
        state.cycle.loopingStatus=1;     % a loop
        state.timer.abort=0;
        setStatusString('Setting up packages...');
        timerCallPackageFunctions('FirstSetup');
        timerMainLoop;
    else
        timerCallPackageFunctions('Abort');
        if ~any(state.timer.packageStatus)    % nothing running
            set(gh.timerMainControls.loop, 'String', 'LOOP');
            set([gh.timerMainControls.doOne gh.timerMainControls.loop], 'Visible', 'on');
        end
    end