Description of timerResumeLoop
Home > Timer > timerResumeLoop.m
timerResumeLoop
PURPOSE
SYNOPSIS
function resumeLoop
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
timerMainLoop
This function is called by:
timerRegisterPackageDone
SOURCE CODE
function resumeLoop
    global state gh
    updateGUIByGlobal('state.internal.secondsCounter');
    state.cycle.repeatsDone=state.cycle.repeatsDone+1;
    updateGUIByGlobal('state.cycle.repeatsDone');
    if state.cycle.randomize
        state.internal.randomPosition=state.internal.randomPosition+1;
    end
    timerMainLoop;