Description of updatePeakDisplay
Home > Timer > updatePeakDisplay.m
updatePeakDisplay
PURPOSE
SYNOPSIS
function updatePeakDisplay
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
This function is called by:
traceAnalyzer TRACEANALYZER M-file for traceAnalyzer.fig
updateLineDisplay
SOURCE CODE
function updatePeakDisplay
    global state
    if state.analysis.displayPeak > size(state.analysis.setup{state.analysis.displayLine, 7}, 1)
        state.analysis.setup{state.analysis.displayLine, 7}(end+1, :)=[1 0 0];
        state.analysis.displayPeak = size(state.analysis.setup{state.analysis.displayLine, 7}, 1);
        updateGUIByGlobal('state.analysis.displayPeak')
    end
    state.analysis.peakMode    = state.analysis.setup{state.analysis.displayLine, 7}(state.analysis.displayPeak, 1);
    state.analysis.peakStart    = state.analysis.setup{state.analysis.displayLine, 7}(state.analysis.displayPeak, 2);
    state.analysis.peakEnd        = state.analysis.setup{state.analysis.displayLine, 7}(state.analysis.displayPeak, 3);
    updateGUIByGlobal('state.analysis.peakMode');
    updateGUIByGlobal('state.analysis.peakStart');
    updateGUIByGlobal('state.analysis.peakEnd');