Description of initTiler
Home > Imaging > tiler > initTiler.m
initTiler
PURPOSE
SYNOPSIS
function initTiler
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
openini
createTilerDAQObjects
makeTilerOutput
tilerAddInputChannels
tilerControls TILERCONTROLS Application M-file for tilerControls.fig
tilerLineControls TILERLINECONTROLS M-file for tilerLineControls.fig
This function is called by:
SOURCE CODE
function initTiler
    global state gh
    gh.tilerControls=guihandles(tilerControls);
    gh.tilerLineControls=guihandles(tilerLineControls);
    openini('tiler.ini');
    createTilerDAQObjects;
    makeTilerOutput;
    tilerAddInputChannels;