Description of saveCurrentConfig
Home > Imaging > io > file_io > configurations > saveCurrentConfig.m
saveCurrentConfig
PURPOSE
SYNOPSIS
function out=saveCurrentConfig()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
createConfigFileFast
This function is called by:
openAndLoadConfiguration Allows user to select a configuration from disk and loads it
opencfg opens and processes a CONFIG (*.CFG) FILE
saveCurrentConfigAs
SOURCE CODE
function out=saveCurrentConfig()
    global state
    out=0;
    [fid, message]=fopen(fullfile(state.configPath, [state.configName '.cfg']), 'wt');
    if fid==-1
        disp(['saveCurrentConfig: Error cannot open output file ' fullfile(state.configPath, [state.configName '.cfg']) ]);
        return
    end
    createConfigFileFast(1, fid, 1);
    fclose(fid);
    out=1;
    state.internal.configurationNeedsSaving=0;