Description of saveCurrentConfigAs
Home > Imaging > io > file_io > configurations > saveCurrentConfigAs.m
saveCurrentConfigAs
PURPOSE
SYNOPSIS
function varargout =saveCurrentConfigAs
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
saveCurrentConfig
makeConfigurationMenu
This function is called by:
SOURCE CODE
function varargout =saveCurrentConfigAs
    global state
    if ~isempty(state.configPath)
        try
            cd(state.configPath)
        catch
        end
    end
    [fname, pname]=uiputfile('*.cfg', 'Choose configuration name');
    if ~isnumeric(fname)
        setStatusString('Saving config...');
        periods=findstr(fname, '.');
        if any(periods)
            fname=fname(1:periods(1)-1);
        end
        state.configName=fname;
        state.configPath=pname;
        updateGUIByGlobal('state.configName');
        saveCurrentConfig;
        makeConfigurationMenu;
        setStatusString('');
        state.internal.configurationNeedsSaving=0;
    else
        setStatusString('Cannot open file');
    end