Description of timerSetup_Imaging
Home > Imaging > timerFunctions > timerSetup_Imaging.m
timerSetup_Imaging
PURPOSE
SYNOPSIS
function timerSetup_Imaging
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
turnOffMenus
resetCounters
applyChangesToOutput
mp285Flush
updateMotorPosition
getPMTOffsets
This function is called by:
SOURCE CODE
function timerSetup_Imaging
    global state
    applyChangesToOutput;
    if state.init.autoReadPMTOffsets
        getPMTOffsets;
    end
    mp285Flush;
    if state.acq.numberOfZSlices > 1
        state.internal.initialMotorPosition=updateMotorPosition;
    else
        state.internal.initialMotorPosition=[];
    end
    resetCounters;
    state.files.lastAcquisition=state.files.fileCounter;
    state.internal.abortActionFunctions=0;
    turnOffMenus;