Description of timerUserSettings_Imaging
Home > Imaging > timerFunctions > timerUserSettings_Imaging.m
timerUserSettings_Imaging
PURPOSE
SYNOPSIS
function timerUserSettings_Imaging
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
loadBlasterSetup
updateKeepAllSlicesCheckMark BSMOD - 1/1/2 - sets check mark next to keepAllSlicesInMemory selection in settings menu
loadConfig
makeConfigurationMenu
reloadPcellTables
This function is called by:
SOURCE CODE
function timerUserSettings_Imaging
    loadConfig;
    updateKeepAllSlicesCheckMark; % BSMOD
    makeConfigurationMenu;
    reloadPcellTables;
    global state
    if ~isempty(state.blaster.setupName) & ~isempty(state.blaster.setupPath)
        loadBlasterSetup(state.blaster.setupPath, state.blaster.setupName)
    end