Description of piezoUpdatePosition
Home > Imaging > io > Piezo > piezoUpdatePosition.m
piezoUpdatePosition
PURPOSE
SYNOPSIS
function piezoUpdatePosition()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
piezoUpdatePositionNoWait
piezoWait
This function is called by:
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
motorGUI MOTORGUI Application M-file for motorGUI.fig
executeGrabOneStackCallback executeGrabOneCallback(h).m******
pzGoto
executeGoHome
startMoveStackFocus
navSelSpine
restoreScan
restoreScanNoStack
SOURCE CODE
function piezoUpdatePosition()
global state
piezoUpdatePositionNoWait();
%wait(state.piezo.Output, state.piezo.tsec+1) ;
piezoWait