Description of calibratePCell
Home > Imaging > pcell > calibratePCell.m
calibratePCell
PURPOSE
SYNOPSIS
function calibratePCell(chan)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
makePcellLookupTable
pcellTest
turnOffAllChildren
turnOnAllChildren
This function is called by:
SOURCE CODE
function calibratePCell(chan)
    if nargin<1
        chan=1;
    end
    global gh
    setStatusString(['Pcell #' num2str(chan) ' calibrate...']);
    turnOffAllChildren(gh.pcellControl.figure1);
    try
        pcellTest(chan);
        makePcellLookupTable(chan);
    catch
        disp(['calibratePCell : Error in pcell calibration : ' lasterr]);
    end
    turnOnAllChildren(gh.pcellControl.figure1);
    setStatusString('Done');