Description of setPcellsToDefault
Home > Imaging > pcell > setPcellsToDefault.m
setPcellsToDefault
PURPOSE
SYNOPSIS
function setPcellsToDefault
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
powerToPcellVoltage
This function is called by:
endAcquisition
applyChangesToOutput
abortFocus
abortGrab
abortPCells
stopAndRestartFocus
SOURCE CODE
function setPcellsToDefault
    global state
    if ~state.pcell.pcellOn
        return
    end
    global pcellFocusOutput pcellGrabOutput
    stop([pcellFocusOutput pcellGrabOutput]);
    vec=[];
    for counter=1:state.pcell.numberOfPcells
        pow=getfield(state.pcell, ['pcellDefaultLevel' num2str(counter)]);
        if pow==-1
          pow=getfield(state.pcell, ['pcellScanning' num2str(counter)]);
        end
        vec(counter)=powerToPcellVoltage(pow, counter);
        vec(counter+state.pcell.numberOfPcells) = 5 * state.shutter.closed;
    end
    putsample(pcellFocusOutput, vec);