Description of resetCounters
Home > Imaging > io > ad_da > resetCounters.m
resetCounters
PURPOSE
SYNOPSIS
function resetCounters
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
This function is called by:
executeFocusCallback
abortFocus
abortGrab
applyImagingInputParams
startFocusForRotation
timerProcess_Imaging
timerSetup_Imaging
SOURCE CODE
function resetCounters
global state
% Function that resets the counters for a new acquisition at the end of acquisitions or ABORT.
    state.internal.frameCounter=0;
    updateGUIByGlobal('state.internal.frameCounter');
    state.internal.stripeCounter=0;
    state.internal.zSliceCounter=0;
    updateGUIByGlobal('state.internal.zSliceCounter');
    if state.pcell.boxSliceSpecific
        state.internal.needNewPcellRepeatedOutput=1;
    end