function out=ivEmptyObjectStruct(nTimepoints, nChan)
	if nargin<2
		nChan=0;
	end
	if isempty(nChan)
		nChan=0;
	end
	if nargin<1
		nTimepoints=0;
	end
	if isempty(nTimepoints)
		nTimepoints=0;
	end
	
	out=struct(...
		'coords', zeros(1, 3), ...
		'status', zeros(1, nTimepoints), ...
		'text', '', ...
		'analysisSlice', zeros(nTimepoints, 1), ...
		'axis1x', zeros(nTimepoints, 2), ...
		'axis1y', zeros(nTimepoints, 2), ...
		'axis2x', zeros(nTimepoints, 2), ...
		'axis2y', zeros(nTimepoints, 2), ...
		'boxX', zeros(nTimepoints, 4), ...
		'boxY', zeros(nTimepoints, 4), ...
		'axisData1', {cell(1, nTimepoints)}, ...
		'axisData2', {cell(1, nTimepoints)}, ...
		'threshold', zeros(1, nTimepoints), ...
		'offset', zeros(1, nTimepoints), ...
		'axisMask1', {cell(1, nTimepoints)}, ...
		'axisMask2', {cell(1, nTimepoints)}, ...
		'boxMask', {cell(1, nTimepoints)}, ...
		'boxROIDef', {cell(1, nTimepoints)}, ...
		'length', zeros(1, nTimepoints), ...
		'width', zeros(1, nTimepoints), ...
		'area', zeros(1, nTimepoints), ...
		'max', zeros(1, nTimepoints), ...
		'results', [], ...
		'boundBoxHandle', [], ...
		'boundBoxLabelHandle', [], ...
		'axisLineHandle1', [], ...
		'axisLineHandle2', [], ...
		'boxHandle', [], ...
		'label', ''...
 		);
