function out=ivEmptyChannelAnalysisStruct(chanList, reps)
	global state
	if nargin<1
		chanList=state.imageViewer.validAnaChannels;
	end
	if nargin<2
		reps=max(state.imageViewer.analyzeBoxes + state.imageViewer.analyzeLines, 1);
	end
	
	nChan=reps*length(chanList);
	
	out=struct(...
		'analysisChannel', zeros(1, nChan), ...
		'morphChannel', zeros(1, nChan), ...
		'isBox', zeros(1, nChan), ...
		'avg', zeros(1, nChan), ...
		'max', zeros(1, nChan), ...
		'size', zeros(1, nChan), ...
		'maskAvg', zeros(1, nChan), ...
		'maskMax', zeros(1, nChan), ...
		'maskSize', zeros(1, nChan)...
		);
		
