function ivHideObjectTraces
	global state
	
	for objectNumber=1:length(state.imageViewer.objStructs);
		handles=[state.imageViewer.objStructs(objectNumber).boundBoxHandle ...
				state.imageViewer.objStructs(objectNumber).boundBoxLabelHandle  ...
				state.imageViewer.objStructs(objectNumber).axisLineHandle1 ...
				state.imageViewer.objStructs(objectNumber).axisLineHandle2 ...
				state.imageViewer.objStructs(objectNumber).boxHandle...
			];
		vHandles=handles(find(ishandle(handles)));
		
		set(vHandles, 'Visible', 'off');
	end
