	setStatusString('Making image windows...');
	
	startImageData = int16(zeros(state.imageViewer.nPixelsY, state.imageViewer.nPixelsX));
	axisPosition = [0 0 1 1];
	aspectRatio = 1;
		
	% This loop creates the appropriate images, figures and axes.
	
	channelList=[1:state.imageViewer.maxChannels 10+(1:state.imageViewer.maxChannels)];
	
	for channelCounter = 1:length(channelList)
		channel=channelList(channelCounter);
		state.imageViewer.figure(channel) = figure(...
			'Position', state.imageViewer.image_position + [360*(channelCounter-1)/2 0 0 0], ...
			'doublebuffer', 'on',...
			'KeyPressFcn', 'ivKeyPressFunction', ...
			'Tag',  ['figure' num2str(channel)], ...
			'Name',  ['Acquisition of Channel ' num2str(channel)], ...
			'NumberTitle', 'off',  ...
			'MenuBar', 'figure', ...
			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
			'visible', 'off', ...
			'ColorMap', makeColorMap('graySat',8) ...
			);
		
		state.imageViewer.axis(channel) = axes(...
			'YDir', 'Reverse', ...
			'NextPlot', 'add', ...
			'XLim', [0 state.imageViewer.nPixelsX], ...
			'YLim', [0 state.imageViewer.nPixelsY], ...
			'CLim', [0 1], ...
			'Parent', state.imageViewer.figure(channel), ...
			'YTickLabelMode', 'manual', ...
			'XTickLabelMode', 'manual', ...
			'Position', axisPosition,  ...
			'XTickLabel', [], ...
			'YTickLabel', [], ...
			'DataAspectRatioMode', 'manual',  ...
			'DataAspectRatio', [aspectRatio 1 1] ...
			);
		
		state.imageViewer.imagehandle(channel) = image(...
			startImageData, ...
			'CDataMapping', 'Scaled', ...
			'Parent', state.imageViewer.axis(channel) ...
			);
		
		
% 		state.imageViewer.coredFigure(channel) = figure(...
% 			'Position', state.imageViewer.image_position + [360*(channelCounter-1)/2 20 0 0], ...
% 			'doublebuffer', 'on',...
% 			'KeyPressFcn', 'ivKeyPressFunction', ...
% 			'Tag',  ['figure' num2str(channel)], ...
% 			'Name',  ['Common Core of Channel ' num2str(channel)], ...
% 			'NumberTitle', 'off',  ...
% 			'MenuBar', 'figure', ...
% 			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
% 			'visible', 'off', ...
% 			'ColorMap', makeColorMap('graySat',8) ...
% 			);
% 		
% 		state.imageViewer.coredAxis(channel) = axes(...
% 			'YDir', 'Reverse', ...
% 			'NextPlot', 'add', ...
% 			'XLim', [0 state.imageViewer.nPixelsX], ...
% 			'YLim', [0 state.imageViewer.nPixelsY], ...
% 			'CLim', [0 1], ...
% 			'Parent', state.imageViewer.coredFigure(channel), ...
% 			'YTickLabelMode', 'manual', ...
% 			'XTickLabelMode', 'manual', ...
% 			'Position', axisPosition,  ...
% 			'XTickLabel', [], ...
% 			'YTickLabel', [], ...
% 			'DataAspectRatioMode', 'manual',  ...
% 			'DataAspectRatio', [aspectRatio 1 1] ...
% 			);
% 		
% 		state.imageViewer.coredImageHandle(channel) = image(...
% 			startImageData, ...
% 			'CDataMapping', 'Scaled', ...
% 			'Parent', state.imageViewer.coredAxis(channel) ...
% 			);
	end
	
	% Same for the max projection windows
	for channelCounter = 1:length(channelList)
		channel=channelList(channelCounter);
		state.imageViewer.projFigure(channel) = figure(...
			'Position', state.imageViewer.projImage_position + [360*(channelCounter-1)/2 0 0 0], ...
			'doublebuffer', 'on',...
			'KeyPressFcn', 'ivKeyPressFunction', ...
			'Tag',  ['projFigure' num2str(channel)], ...
			'Name',  ['Projection of Channel ' num2str(channel)], ...
			'NumberTitle', 'off',  ...
			'MenuBar', 'figure', ...
			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
			'visible', 'off', ...
			'ColorMap', makeColorMap('graySat',8) ...
			);
				
		state.imageViewer.projAxis(channel) = axes(...
			'YDir', 'Reverse', ...
			'NextPlot', 'add', ...
			'XLim', [0 state.imageViewer.nPixelsX], ...
			'YLim', [0 state.imageViewer.nPixelsY], ...
			'CLim', [0 1], ...
			'Parent', state.imageViewer.projFigure(channel), ...
			'YTickLabelMode', 'manual', ...
			'XTickLabelMode', 'manual', ...
			'Position', axisPosition,  ...
			'XTickLabel', [], ...
			'YTickLabel', [], ...
			'DataAspectRatioMode', 'manual',  ...
			'DataAspectRatio', [aspectRatio 1 1] ...
			);
			
		state.imageViewer.projImagehandle(channel) = image(...
			startImageData, ...
			'CDataMapping', 'Scaled', ...
			'Parent', state.imageViewer.projAxis(channel) ...
			);
	end
	
	state.imageViewer.compositeFigure = figure(...
		'Position', state.imageViewer.compositeImage_position, ...
		'doublebuffer', 'on',...
		'KeyPressFcn', 'ivKeyPressFunction', ...
		'Tag',  'CompositeFigure', ...
		'Name',  'Composite', ...
		'NumberTitle', 'off',  ...
		'MenuBar', 'figure', ...
		'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
		'visible', 'off' ...
		);
	
	state.imageViewer.compositeAxis = axes(...
		'YDir', 'Reverse',...
		'NextPlot', 'add', ...
		'XLim', [0 state.imageViewer.nPixelsX], ...
		'YLim', [0 state.imageViewer.nPixelsY], ...
		'CLim', [0 1], ...
		'Parent', state.imageViewer.compositeFigure, ...
		'YTickLabelMode', 'manual', ...
		'XTickLabelMode', 'manual', ...
		'Position', axisPosition,  ...
		'XTickLabel', [], ...
		'YTickLabel', [], ...
		'DataAspectRatioMode', 'manual',  ...
		'DataAspectRatio', [aspectRatio 1 1]...
		);
		
	state.imageViewer.compositeImagehandle = image(...
		zeros(state.imageViewer.nPixelsY, state.imageViewer.nPixelsX, 3), ...
		'Parent', state.imageViewer.compositeAxis...
		);

	state.imageViewer.referenceFigure = figure(...
		'Position', state.imageViewer.compositeImage_position, ...
		'doublebuffer', 'on',...
		'KeyPressFcn', 'ivKeyPressFunction', ...
		'Tag',  'referenceFigure', ...
		'Name',  'reference', ...
		'NumberTitle', 'off',  ...
		'MenuBar', 'figure', ...
		'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
		'visible', 'off' ...
		);
	
	state.imageViewer.referenceAxis = axes(...
		'YDir', 'Reverse',...
		'NextPlot', 'add', ...
		'XLim', [0 state.imageViewer.nPixelsX], ...
		'YLim', [0 state.imageViewer.nPixelsY], ...
		'CLim', [0 1], ...
		'Parent', state.imageViewer.referenceFigure, ...
		'YTickLabelMode', 'manual', ...
		'XTickLabelMode', 'manual', ...
		'Position', axisPosition,  ...
		'XTickLabel', [], ...
		'YTickLabel', [], ...
		'DataAspectRatioMode', 'manual',  ...
		'DataAspectRatio', [aspectRatio 1 1]...
		);
		
	state.imageViewer.referenceData=zeros(state.imageViewer.nPixelsY, state.imageViewer.nPixelsX, 3);
	state.imageViewer.referenceImagehandle = image(...
		state.imageViewer.referenceData, 'Parent', state.imageViewer.referenceAxis...
		);
		
	setStatusString('');
