function ivResumeTimeSeries
	global state
	fieldsToSave={...
			         'filePath', ...
				'fileBaseName', ...
              'tsNumberOfFiles', ...
                   'tsFileNames', ...
                   'tsFilePaths', ...
               'tsStackHeader', ...
                   'tsStackData', ...
                       'tsShift', ...
                    'tsMinShift', ...
                    'tsMaxShift', ...
                'tsDataRangeLow', ...
               'tsDataRangeHigh', ...
              'tsCoredStackData', ...
         'tsCoredFlatProjection', ...
    'tsCoredFlatProjectionIndex', ...
              'objectShowTraces', ...
              'objectAutoCenter', ...
                 'objectCenters', ...
                       'offsets', ...
                 'referenceData', ...
           'displayedSliceSmear', ...
                      'nPixelsX', ...
                      'nPixelsY', ...
                     'hwChannel', ...
             'selectionChannel', ...
                    'offsetMode', ...
                'smoothingWidth', ...
                 'widthFraction', ...
                  'numTopPixels', ...
                  'objectStatus', ...
              'objectMajorAxisX', ...
              'objectMajorAxisY', ...
              'objectMinorAxisX', ...
              'objectMinorAxisY', ...
            'objectMajorProfile', ...
               'objectMajorMask', ...
            'objectMinorProfile', ...
               'objectMinorMask', ...
                  'objectLength', ...
                   'objectWidth', ...
                    'objectMass', ...
                  'objectThresh', ...
           'projectionIndexData', ...
             'projectionDataAll', ...
            'trackerReferenceXZ', ...
            'trackerReferenceYZ', ...
                      'lineBlur', ...
                   'channelOn1', ...
                    'channelOn2', ...
                    'channelOn3', ...
                    'channelOn4', ...
                    'channelsOn', ...
	                         'zoom', ...
               'micronsPerSlice', ...
              'micronsPerPixelX', ...
              'micronsPerPixelY', ...
                   'anaChannel1', ...
                   'anaChannel2', ...
                   'anaChannel3', ...
                   'anaChannel4', ...
                'anaProjection1', ...
                'anaProjection2', ...
                'anaProjection3', ...
                'anaProjection4', ...
                  'anaChannel11', ...
                  'anaChannel12', ...
                  'anaChannel13', ...
                  'anaChannel14', ...
               'anaProjection11', ...
               'anaProjection12', ...
               'anaProjection13', ...
               'anaProjection14', ...
                    'analyzeBox', ...				  
				  };

	[fname, pname] = uigetfile([state.imageViewer.fileBaseName '_ts.mat'], 'Choose data file...');
	if pname == 0
		return
	end

	disp('Loading...')
	S=load([pname fname]');

	timeSeriesData=[];
	for field=fieldsToSave
		eval(['state.imageViewer.' field{1} '=S.timeSeriesData.' field{1} ';']);
		updateGUIByGlobal(['state.imageViewer.' field{1}]);
	end
	clear timeSeriesData
			
	state.imageViewer.currentObject=1;
	updateGUIByGlobal('state.imageViewer.currentObject');
	ivFlipTimeSeries(1);
	
	disp('Done...');

			  