function initPcellBoxSettingsManager
	settingsManager(1, 'pcellBox', {...
		'state.pcell.boxStartX', ...
		'state.pcell.boxStartY', ...
		'state.pcell.boxEndX', ...	
		'state.pcell.boxEndY', ...
		'state.pcell.boxPowerLevel1', ...
		'state.pcell.boxPowerLevel2', ...
		'state.pcell.boxActiveStatus', ...
		'state.pcell.boxFrameNumber', ...
		'state.pcell.boxSliceNumber', ...
	})