function updateCurrentBox
	global state gh
	
	if ishandle(state.pcell.currentBoxHandle)
		set(state.pcell.currentBoxHandle, 'XData', ...
			[state.pcell.currentStartX state.pcell.currentEndX state.pcell.currentEndX ...
				state.pcell.currentStartX state.pcell.currentStartX]);
		set(state.pcell.currentBoxHandle, 'YData', ...
			[state.pcell.currentStartY state.pcell.currentStartY state.pcell.currentEndY ...
				state.pcell.currentEndY state.pcell.currentStartY]);
	end
	storeBoxSettings;
