Description of checkCurrentCycleInMenu
Home > Physiology > checkCurrentCycleInMenu.m
checkCurrentCycleInMenu
PURPOSE
SYNOPSIS
function checkCurrentCycleInMenu(name)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
loadPhysCycle
loadPhysCycleFromMemory writes pulseSet to disk
savePhysCycleAs save pulse set to disk with new name
SOURCE CODE
function checkCurrentCycleInMenu(name)
    global state gh
    if nargin<1
        name=state.cycle.cycleName;
    end
    children=get(gh.timerMainControls.Cycles, 'Children');
    index=find(strcmp(get(children, 'Label'), name));
    set(children, 'Checked', 'off');
    if ~isempty(index)
        set(children(index), 'Checked', 'on');
    end