Description of phSetDAQRates
Home > Physiology > phSetDAQRates.m
phSetDAQRates
PURPOSE
SYNOPSIS
function phSetDAQRates
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
physsettings PHYSSETTINGS Application M-file for physSettings.fig
initPhys
timerUserSettings_Physiology
SOURCE CODE
function phSetDAQRates
    global state physOutputDevice physAuxOutputDevice physInputDevice
    state.phys.settings.inputRate=setverify(physInputDevice, 'SampleRate', state.phys.settings.inputRate);
    updateGUIByGlobal('state.phys.settings.inputRate');
    state.phys.settings.outputRate=setverify(physOutputDevice, 'SampleRate', state.phys.settings.outputRate);
    if state.phys.daq.auxOutputBoardIndex>0
        outputRate=setverify(physAuxOutputDevice, 'SampleRate', state.phys.settings.outputRate);
        state.phys.internal.needNewAuxOutputData=1;
    end
    state.phys.internal.needNewOutputData=1;
    updateGUIByGlobal('state.phys.settings.outputRate');