Description of physAvgName
Home > Physiology > physAvgName.m
physAvgName
PURPOSE
SYNOPSIS
function out=physAvgName(epoch, channel, pulse)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
phEndAcquisitionProcessing
phResetAverages
physAvgList
seeAverages
seeAveragesMultiPanel
SOURCE CODE
function out=physAvgName(epoch, channel, pulse)
    global state
    if isnumeric(epoch)
        epoch=num2str(epoch);
    end
    if isnumeric(channel)
        channel=num2str(channel);
    end
    if isnumeric(pulse)
        pulse=num2str(pulse);
    end
    out=[getfield(state.phys.settings, ['ADPrefix' channel]) '_' 'e' epoch 'p' pulse 'avg'];