Description of readTelegraphs
Home > Physiology > readTelegraphs.m
readTelegraphs
PURPOSE
SYNOPSIS
function readTelegraphs
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
phSetChannelGains
readAxonTelegraphs
readMultiClampParams
This function is called by:
startScopeLoop
timerSetup_Physiology
timerWait_Physiology
SOURCE CODE
function readTelegraphs
    global state
    readAxon=0;
    for counter=0:1
        type=getfield(state.phys.settings, ['channelType' num2str(counter)]);
        switch type
        case 2
            if ~readAxon
                readAxonTelegraphs;
                readAxon=1;
            end
        case 3
            readMultiClampParams(counter);
        end
    end
    phSetChannelGains