Description of savePhysCycle
Home > Physiology > savePhysCycle.m
savePhysCycle
PURPOSE
writes pulseSet to disk
SYNOPSIS
function savePhysCycle
DESCRIPTION
 writes pulseSet to disk
CROSS-REFERENCE INFORMATION
This function calls:
savePhysCycleAs save pulse set to disk with new name
setPhysStatusString
This function is called by:
physcyclegui PHYSCYCLEGUI Application M-file for physcyclegui.fig
savePhysCycleAs save pulse set to disk with new name
SOURCE CODE
function savePhysCycle
% writes pulseSet to disk
    global state
    if isempty(state.phys.cycle.cyclePath) | isempty(state.phys.cycle.cycleName)
        savePhysCycleAs;
    else
        cycle.cycleDef=state.phys.cycle.cycleDef;
        cycle.rsPulseVC=state.phys.cycle.rsPulseVC;
        cycle.rsPulseCC=state.phys.cycle.rsPulseCC;
        save(fullfile(state.phys.cycle.cyclePath, state.phys.cycle.cycleName), 'cycle', '-MAT');
        setPhysStatusString('cycle saved');
    end