Description of mp285Flush
Home > Imaging > io > motors > MP285 > mp285Flush.m
mp285Flush
PURPOSE
SYNOPSIS
function temp=mp285Flush
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
executeFocusCallback
mp285GetPos mp285GetPos retrieves the position information from the mp285 controller
mp285SetPos mp285SetPos controls the position of the mp285
mp285SetVelocity
mp285StartMove mp285SetPos controls the position of the mp285
abortFocus
abortGrab
timerSetup_Imaging
SOURCE CODE
function temp=mp285Flush
temp=[];
try
    global state
    state.motor.positionPending=0;
    state.motor.movePending=0;
    if state.motor.motorOn==0
        return
    end
    if length(state.motor.serialPortHandle) == 0
        disp(['MP285Talk: MP285 not configured']);
        return;
    end
    n=get(state.motor.serialPortHandle,'BytesAvailable');
    if  n > 0
        temp=fread(state.motor.serialPortHandle,n);
    end
catch
end