Description of saveBlasterSetup
Home > Imaging > blaster > saveBlasterSetup.m
saveBlasterSetup
PURPOSE
SYNOPSIS
function saveBlasterSetup
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
blaster BLASTER M-file for blaster.fig
saveBlasterSetupAs save pulse set to disk with new name
setStatusString This function sets the status field in mainControls.
This function is called by:
saveBlasterSetupAs save pulse set to disk with new name
SOURCE CODE
function saveBlasterSetup
    global state
    if isempty(state.blaster.setupPath) | isempty(state.blaster.setupName)
        saveBlasterSetupAs;
    else
        blaster=[];
        for field=state.blaster.paramList
            blaster=setfield(blaster, field{1}, getfield(state.blaster, field{1}));
        end
         save(fullfile(state.blaster.setupPath, state.blaster.setupName), 'blaster', '-MAT');
        setStatusString('Blaster setup saved');
    end