Description of siSelectionChannelToFront
Home > Imaging > guis > siSelectionChannelToFront.m
siSelectionChannelToFront
PURPOSE
SYNOPSIS
function siSelectionChannelToFront
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fluorAnalysisSettings FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
ratios RATIOS M-file for ratios.fig
blaster BLASTER M-file for blaster.fig
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
multiBlaster
pickAndMove
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
pickPcellBoxCenters
traceAnalyzer TRACEANALYZER M-file for traceAnalyzer.fig
SOURCE CODE
function siSelectionChannelToFront
    global state
    if state.internal.selectionChannel<=4
        figure(state.internal.GraphFigure(state.internal.selectionChannel));
    elseif state.internal.selectionChannel==5
        figure(state.internal.refFigure);
    elseif state.internal.selectionChannel==6
        figure(state.internal.compositeFigure);
    end