Description of checkValidNumber
Home > Imaging > guis > gui_handling > checkValidNumber.m
checkValidNumber
PURPOSE
function to check if entry in GUI is valid
SYNOPSIS
function out=checkValidNumber(handle)
DESCRIPTION
 function to check if entry in GUI is valid
CROSS-REFERENCE INFORMATION
This function calls:
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
setUserDataField sets fields in 'UserData' of a handle. Varargin should be field1, value1 [, field2, value2 ...]
This function is called by:
genericCallback
SOURCE CODE
function out=checkValidNumber(handle)
% function to check if entry in GUI is valid
    out=1;
    style=get(handle, 'Style');
    min=[];
    max=[];
    valField=[];
    if strcmp(style, 'slider')
        val=get(handle, 'Value');
        valField='Value';
        min=get(handle, 'Min');
        max=get(handle, 'Max');
    elseif strcmp(style, 'edit')
        if hasUserDataField(handle, 'Numeric')
            if ~getUserDataField(handle, 'Numeric')
                return
            end
            val=str2double(get(handle, 'String'));
        else
%             val=str2double(get(handle, 'String'));
%             if length(val)~=1
                return
%             end
        end
        valField='String';
        min=getUserDataField(handle, 'Min');
        max=getUserDataField(handle, 'Max');
    elseif strcmp(style, 'popupmenu')
        val=get(handle, 'Value');
        valField='Value';
        min=1;
        max=length(get(handle, 'String'));
    elseif strcmp(style, 'checkbox') || strcmp(style, 'radiobutton')
        val=get(handle, 'Value');
    elseif strcmp(style, 'text')
        return
    else
        disp(['checkValidNUmber: Unimplemented style :' style]);
    end
    if isnumeric(val) && length(val)==1
        if length(min)==1
            if (val < min)
                val=min;
            end
        end
        if length(max)==1
            if (val > max)
                val=max;
            end
        end
        if strcmp(style, 'edit')
            val=num2str(val);
        end
        if ~isempty(valField)
            set(handle, valField, val);
        end
        setUserDataField(handle, 'LastValid', val);
    elseif strcmp(style, 'edit')
        if hasUserDataField(handle, 'LastValid')
            set(handle, 'String', getUserDataField(handle, 'LastValid'));
        else
            set(handle, 'String', '0');
            out=0;
        end
    elseif strcmp(style, 'slider')
        if hasUserDataField(handle, 'LastValid')
            set(handle, 'Value', getUserDataField(handle, 'LastValid'));
        else
            out=0;
        end
    end