Description of doGUICallback
Home > Imaging > guis > gui_handling > doGUICallback.m
doGUICallback
PURPOSE
calls the Callback function of a GUI if one has been set by the user
SYNOPSIS
function doGUICallback(handle)
DESCRIPTION
 calls the Callback function of a GUI if one has been set by the user
CROSS-REFERENCE INFORMATION
This function calls:
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
This function is called by:
genericCallback
SOURCE CODE
function doGUICallback(handle)
% calls the Callback function of a GUI if one has been set by the user
    if hasUserDataField(handle, 'Callback')
        funcName=getUserDataField(handle, 'Callback');
        if exist(funcName)==2
            try
                eval([funcName '(handle);']);
            catch
                disp(['doGUICallBack: ' lasterr ' in ' funcName ]);
            end
        else
            if length(funcName)>0
                disp(['doGUICallback: Callback function (' funcName ') does not exist. No action.']);
            end
        end
    end