Description of existGlobal
Home > Imaging > guis > gui_handling > existGlobal.m
existGlobal
PURPOSE
SYNOPSIS
function out=existGlobal(globalName)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
existGlobal
structNameParts
This function is called by:
existGlobal
initGUIs opens and interprets and initialization file
initGUIs_OLD opens and interprets and initialization file
SOURCE CODE
function out=existGlobal(globalName)
    out=0;
    [topName, structName, fieldName]=structNameParts(globalName);
    eval(['global ' topName]);
    if eval(['exist(''' topName ''')'])
        if length(fieldName)==0
            out=1;
        else
            if length(structName)>length(topName)
                if existGlobal(structName)
                    if eval(['isfield(' structName ',''' fieldName ''');'])
                        out=1;
                    end
                end
            else
                if eval(['isfield(' structName ',''' fieldName ''');'])
                    out=1;
                end
            end
        end
    end