Description of genericCallback
Home > Imaging > guis > gui_handling > genericCallback.m
genericCallback
PURPOSE
SYNOPSIS
function genericCallback(handle)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
checkValidNumber function to check if entry in GUI is valid
doGUICallback calls the Callback function of a GUI if one has been set by the user
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGUILinks
This function is called by:
fluorAnalysisSettings FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
blaster BLASTER M-file for blaster.fig
advancedCycleGUI ADVANCEDCYCLEGUI M-file for advancedCycleGUI.fig
basicConfigurationGUI BASICCONFIGURATIONGUI_OLD Application M-file for configurationGUI.fig
channelGUI
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
imageGUI IMAGEGUI Application M-file for imageGUI.fig
imageTracker IMAGETRACKER M-file for imageTracker.fig
motorGUI MOTORGUI Application M-file for motorGUI.fig
siGUI_ImagingControls siGUI_ImagingControls Application M-file for siGUI_ImagingControls.fig
setUserDataField sets fields in 'UserData' of a handle. Varargin should be field1, value1 [, field2, value2 ...]
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
tilerControls TILERCONTROLS Application M-file for tilerControls.fig
tilerLineControls TILERLINECONTROLS M-file for tilerLineControls.fig
timerMainControls TIMERMAINCONTROLS M-file for timerMainControls.fig
traceAnalyzer TRACEANALYZER M-file for traceAnalyzer.fig
SOURCE CODE
function genericCallback(handle)
    checkValidNumber(handle);
    updateGUIGlobal(handle);
    updateGUILinks(handle);
    doGUICallback(handle);