function saveScan(varargin)

	global state
	
	if(nargin==0)
	
		try
			pos=state.internal.saveScanLastPos+1;
		catch
			pos=1;
			state.internal.saveScanLastPos=pos;
		end
	
	else
		pos=varargin{1};
	end

	if(state.internal.saveScanLastPos<pos)
		state.internal.saveScanLastPos=pos;
    end
    
    updateMotorPosition;
		 	
	relevantInfo=[...
		state.acq.zoomFactor ...
		state.acq.scanRotation ...
		state.acq.postRotOffsetX ...
		state.acq.postRotOffsetY...
		state.internal.trackerX0 ...
		state.internal.trackerY0 ...
		state.acq.scanShiftX ...
		state.acq.scanShiftY ...
		state.acq.pixelShiftX ...
		state.acq.pixelShiftY ...
		state.internal.refShiftX ...
		state.internal.refShiftY ...
		state.piezo.last_pos ...
        state.motor.relZPosition ...
	];

	state.internal.saveScanInfo(pos, :)=relevantInfo;
	state.internal.trackerReferences{pos} = state.acq.trackerReference;
	state.acq.trackerReferencesAll{pos} = state.acq.trackerReferenceAll;	