Description of gotoZero
Home > Imaging > io > motors > gotoZero.m
gotoZero
PURPOSE
SYNOPSIS
function gotoZero
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
mp285SetVelocity
setMotorPosition
updateRelativeMotorPosition
This function is called by:
genericKeyPressFunction
SOURCE CODE
function gotoZero
    global state
    setStatusString('Moving to (0,0,0)');
    mp285SetVelocity(state.motor.velocityFast);
    state.motor.absXPosition=state.motor.offsetX;
    state.motor.absYPosition=state.motor.offsetY;
    state.motor.absZPosition=state.motor.offsetZ;
    setMotorPosition;
    updateRelativeMotorPosition;
    mp285SetVelocity(state.motor.velocitySlow);
    disp(['*** Staged moved to relative (0,0,0) ***']);
    setStatusString('');