Description of updateRelativeMotorPosition
Home > Imaging > io > motors > updateRelativeMotorPosition.m
updateRelativeMotorPosition
PURPOSE
SYNOPSIS
function updateRelativeMotorPosition(update)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
This function is called by:
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
motorGUI MOTORGUI Application M-file for motorGUI.fig
executeGrabOneStackCallback executeGrabOneCallback(h).m******
genericKeyPressFunction
executeGoHome
gotoPosition
gotoZero
updateMotorPosition
SOURCE CODE
function updateRelativeMotorPosition(update)
    if nargin<1
        update=1;
    end
    global state
    state.motor.relXPosition = state.motor.absXPosition - state.motor.offsetX; % Calculate absoluteX Position
    state.motor.relYPosition = state.motor.absYPosition - state.motor.offsetY; % Calculate absoluteY Position
    state.motor.relZPosition = state.motor.absZPosition - state.motor.offsetZ; % Calculate absoluteZ Position
    state.motor.distance=sqrt(state.motor.relXPosition^2+state.motor.relYPosition^2+state.motor.relZPosition^2);
    if update
        updateGUIByGlobal('state.motor.relXPosition');
        updateGUIByGlobal('state.motor.relYPosition');
        updateGUIByGlobal('state.motor.relZPosition');
        updateGUIByGlobal('state.motor.distance');
    end