function updateimageGUI
global state gh


for channelCounter = 1:state.init.maximumNumberOfInputChannels
	if state.acq.acquiringChannel(channelCounter) 
		set([getfield(gh.imageGUI, ['highPixelValueSlider' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValueSlider' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['highPixelValue' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValue' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['whiteTag' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['blackTag' num2str(channelCounter)])] ...
			, 'Enable', 'On');	
		if state.acq.dualLaserMode>1
			set([getfield(gh.imageGUI, ['highPixelValueSlider' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['lowPixelValueSlider' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['highPixelValue' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['lowPixelValue' num2str(10+channelCounter)])] ...
				, 'Enable', 'On');			
		else
			set([getfield(gh.imageGUI, ['highPixelValueSlider' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['lowPixelValueSlider' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['highPixelValue' num2str(10+channelCounter)]) ...
				getfield(gh.imageGUI, ['lowPixelValue' num2str(10+channelCounter)])] ...
				, 'Enable', 'Off');			
		end			
	else
		set([getfield(gh.imageGUI, ['highPixelValueSlider' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValueSlider' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['highPixelValue' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValue' num2str(channelCounter)]) ...			
			getfield(gh.imageGUI, ['whiteTag' num2str(channelCounter)]) ...
			getfield(gh.imageGUI, ['blackTag' num2str(channelCounter)])] ...
			, 'Enable', 'Off');
		set([getfield(gh.imageGUI, ['highPixelValueSlider' num2str(10+channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValueSlider' num2str(10+channelCounter)]) ...
			getfield(gh.imageGUI, ['highPixelValue' num2str(10+channelCounter)]) ...
			getfield(gh.imageGUI, ['lowPixelValue' num2str(10+channelCounter)])] ...
			, 'Enable', 'Off');
	end
end
