Description of makeImageFigures
Home > Imaging > guis > gui_building > makeImageFigures.m
makeImageFigures
PURPOSE
SYNOPSIS
function makeImageFigures
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
makeColorMap
setStatusString This function sets the status field in mainControls.
setupScanImageFigurePositions
This function is called by:
initImaging
SOURCE CODE
function makeImageFigures
    global state
    setStatusString('Making image windows...');
    startImageData = int16(zeros(state.acq.linesPerFrame, state.acq.pixelsPerLine));
    axisPosition = [0 0 1 1];
    aspectRatio = state.internal.imageAspectRatioBias*state.acq.scanAmplitudeY/state.acq.scanAmplitudeX; % /(state.acq.linesPerFrame/state.acq.pixelsPerLine);
    setupScanImageFigurePositions;
    % This loop creates the appropriate images, figures and axes.
    channelList=[1:state.init.maximumNumberOfInputChannels 11:10+state.init.maximumNumberOfInputChannels];
    for channelCounter = channelList
        state.internal.GraphFigure(channelCounter) = figure(...
            'Position', eval(['state.windowPositions.image' num2str(channelCounter) '_position']), ...
            'doublebuffer', 'on',...
            'KeyPressFcn', 'genericKeyPressFunction', ...
            'Tag',  ['GraphFigure' num2str(channelCounter)], ...
            'Name',  ['Acquisition of Channel ' num2str(channelCounter)], ...
            'NumberTitle', 'off',  ...
            'MenuBar', 'none', ...
            'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
            'visible', 'off', ...
            'ColorMap', makeColorMap('graySat',8) ...
            );
        state.internal.axis(channelCounter) = axes(...
            'YDir', 'Reverse', ...
            'NextPlot', 'add', ...
            'XLim', [0 state.acq.pixelsPerLine], ...
            'YLim', [0 state.acq.linesPerFrame], ...
            'CLim', [0 1], ...
            'Parent', state.internal.GraphFigure(channelCounter), ...
            'YTickLabelMode', 'manual', ...
            'XTickLabelMode', 'manual', ...
            'Position', axisPosition,  ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'DataAspectRatioMode', 'manual',  ...
            'DataAspectRatio', [aspectRatio 1 1], ...
            'ButtonDownFcn', 'figureButtonOverCallback',...
            'xlimmode','manual',...
            'ylimmode','manual',...
            'zlimmode','manual',...
            'climmode','manual',...
            'alimmode','manual'...
            );
        state.internal.imagehandle(channelCounter) = image(...
            startImageData, ...
            'CDataMapping', 'Scaled', ...
            'Parent', state.internal.axis(channelCounter), ...
            'ButtonDownFcn', 'figureButtonOverCallback'...
            );
    end
    % Same for the max projection windows
    for channelCounter = channelList
        state.internal.MaxFigure(channelCounter) = figure(...
            'Position', eval(['state.windowPositions.maxImage' num2str(channelCounter) '_position']), ...
            'doublebuffer', 'off',...
            'KeyPressFcn', 'genericKeyPressFunction', ...
            'Tag',  ['MaxFigure' num2str(channelCounter)], ...
            'Name',  ['Max Projection of Channel ' num2str(channelCounter)], ...
            'NumberTitle', 'off',  ...
            'MenuBar', 'none', ...
            'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
            'visible', 'off', ...
            'ColorMap', makeColorMap('graySat',8) ...
            );
        state.internal.maxaxis(channelCounter) = axes(...
            'YDir', 'Reverse', ...
            'NextPlot', 'add', ...
            'XLim', [0 state.acq.pixelsPerLine], ...
            'YLim', [0 state.acq.linesPerFrame], ...
            'CLim', [0 1], ...
            'Parent', state.internal.MaxFigure(channelCounter), ...
            'YTickLabelMode', 'manual', ...
            'XTickLabelMode', 'manual', ...
            'Position', axisPosition,  ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'DataAspectRatioMode', 'manual',  ...
            'DataAspectRatio', [aspectRatio 1 1], ...
            'ButtonDownFcn', 'figureButtonOverCallback'...
            );
        state.internal.maximagehandle(channelCounter) = image(...
            startImageData, ...
            'CDataMapping', 'Scaled', ...
            'Parent', state.internal.maxaxis(channelCounter), ...
            'ButtonDownFcn', 'figureButtonOverCallback'...
            );
    end
    state.internal.compositeFigure = figure(...
        'Position', state.windowPositions.compositeImage_position, ...
        'doublebuffer', 'off',...
        'KeyPressFcn', 'genericKeyPressFunction', ...
        'Tag',  'CompositeFigure', ...
        'Name',  'Composite', ...
        'NumberTitle', 'off',  ...
        'MenuBar', 'none', ...
        'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
        'visible', 'off' ...
        );
    state.internal.compositeAxis = axes(...
        'YDir', 'Reverse',...
        'NextPlot', 'add', ...
        'XLim', [0 state.acq.pixelsPerLine], ...
        'YLim', [0 state.acq.linesPerFrame], ...
        'CLim', [0 1], ...
        'Parent', state.internal.compositeFigure, ...
        'YTickLabelMode', 'manual', ...
        'XTickLabelMode', 'manual', ...
        'Position', axisPosition,  ...
        'XTickLabel', [], ...
        'YTickLabel', [], ...
        'DataAspectRatioMode', 'manual',  ...
        'DataAspectRatio', [aspectRatio 1 1]...
        );
    state.internal.compositeImagehandle = image(...
        zeros(state.acq.linesPerFrame, state.acq.pixelsPerLine, 3), ...
        'Parent', state.internal.compositeAxis...
        );
    setStatusString('');