Description of fluorAnalysisSettings
Home > Imaging > FluoProcessing > fluorAnalysisSettings.m
fluorAnalysisSettings
PURPOSE
FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
SYNOPSIS
function varargout = fluorAnalysisSettings(varargin)
DESCRIPTION
 FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
      FLUORANALYSISSETTINGS, by itself, creates a new FLUORANALYSISSETTINGS or raises the existing
      singleton*.
      H = FLUORANALYSISSETTINGS returns the handle to a new FLUORANALYSISSETTINGS or the handle to
      the existing singleton*.
      FLUORANALYSISSETTINGS('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in FLUORANALYSISSETTINGS.M with the given input arguments.
      FLUORANALYSISSETTINGS('Property','Value',...) creates a new FLUORANALYSISSETTINGS or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before fluorAnalysisSettings_OpeningFunction gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to fluorAnalysisSettings_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
reviewFluorData
runFluorAnalysis
genericCallback
setStatusString This function sets the status field in mainControls.
siSelectionChannelToFront
This function is called by:
initFluorAnalysis
SUBFUNCTIONS
function fluorAnalysisSettings_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = fluorAnalysisSettings_OutputFcn(hObject, eventdata, handles)
function ratioMode1_CreateFcn(hObject, eventdata, handles)
function ratioMode2_CreateFcn(hObject, eventdata, handles)
function ratioMode3_CreateFcn(hObject, eventdata, handles)
function physiologyLinkDA_CreateFcn(hObject, eventdata, handles)
function numberOfROI_CreateFcn(hObject, eventdata, handles)
function avgLineScanStart_CreateFcn(hObject, eventdata, handles)
function avgLineScanStart_Callback(hObject, eventdata, handles)
function avgLineScanEnd_CreateFcn(hObject, eventdata, handles)
function avgLineScanSmooth_CreateFcn(hObject, eventdata, handles)
function baselineStart_CreateFcn(hObject, eventdata, handles)
function baselineEnd_CreateFcn(hObject, eventdata, handles)
function baseFrameStart_CreateFcn(hObject, eventdata, handles)
function baseFrameEnd_CreateFcn(hObject, eventdata, handles)
function varargout = generic_Callback(h, eventdata, handles, varargin)
function analysisMode_CreateFcn(hObject, eventdata, handles)
function avgLineScanChannel_CreateFcn(hObject, eventdata, handles)
function baseLineEnd_CreateFcn(hObject, eventdata, handles)
function baseLineStart_CreateFcn(hObject, eventdata, handles)
function numberOfROISlider_CreateFcn(hObject, eventdata, handles)
function avgLineScanStartSlider_CreateFcn(hObject, eventdata, handles)
function avgLineScanEndSlider_CreateFcn(hObject, eventdata, handles)
function avgLineScanSmoothSlider_CreateFcn(hObject, eventdata, handles)
function baseLineStartSlider_CreateFcn(hObject, eventdata, handles)
function baseLineEndSlider_CreateFcn(hObject, eventdata, handles)
function baseFrameStartSlider_CreateFcn(hObject, eventdata, handles)
function baseFrameEndSlider_CreateFcn(hObject, eventdata, handles)
function roiWidth_CreateFcn(hObject, eventdata, handles)
function roiWidth_Callback(hObject, eventdata, handles)
function roiWidthSlider_CreateFcn(hObject, eventdata, handles)
function review_Callback(hObject, eventdata, handles)
function epoch_CreateFcn(hObject, eventdata, handles)
function epochSlider_CreateFcn(hObject, eventdata, handles)
function review_CreateFcn(hObject, eventdata, handles)
function reviewSlider_CreateFcn(hObject, eventdata, handles)
function selectROIButton_Callback(hObject, eventdata, handles)
function currentROINumber_CreateFcn(hObject, eventdata, handles)
function currentROINumber_Callback(hObject, eventdata, handles)
function currentROINumberSlider_CreateFcn(hObject, eventdata, handles)
function rerunButton_Callback(hObject, eventdata, handles)
function peakStart_CreateFcn(hObject, eventdata, handles)
function peakStart_Callback(hObject, eventdata, handles)
function peakEnd_CreateFcn(hObject, eventdata, handles)
function peakEnd_Callback(hObject, eventdata, handles)
function peakAverage_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = fluorAnalysisSettings(varargin)
% FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
%      FLUORANALYSISSETTINGS, by itself, creates a new FLUORANALYSISSETTINGS or raises the existing
%      singleton*.
%
%      H = FLUORANALYSISSETTINGS returns the handle to a new FLUORANALYSISSETTINGS or the handle to
%      the existing singleton*.
%
%      FLUORANALYSISSETTINGS('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in FLUORANALYSISSETTINGS.M with the given input arguments.
%
%      FLUORANALYSISSETTINGS('Property','Value',...) creates a new FLUORANALYSISSETTINGS or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before fluorAnalysisSettings_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to fluorAnalysisSettings_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help fluorAnalysisSettings
% Last Modified by GUIDE v2.5 06-Mar-2003 10:34:03
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @fluorAnalysisSettings_OpeningFcn, ...
                   'gui_OutputFcn',  @fluorAnalysisSettings_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin & isstr(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before fluorAnalysisSettings is made visible.
function fluorAnalysisSettings_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to fluorAnalysisSettings (see VARARGIN)
% Choose default command line output for fluorAnalysisSettings
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes fluorAnalysisSettings wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = fluorAnalysisSettings_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes during object creation, after setting all properties.
function ratioMode1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to ratioMode1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function ratioMode2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to ratioMode2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function ratioMode3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to ratioMode3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function physiologyLinkDA_CreateFcn(hObject, eventdata, handles)
% hObject    handle to physiologyLinkDA (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function numberOfROI_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numberOfROI (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanStart_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function avgLineScanStart_Callback(hObject, eventdata, handles)
% hObject    handle to avgLineScanStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of avgLineScanStart as text
%        str2double(get(hObject,'String')) returns contents of avgLineScanStart as a double
% --- Executes during object creation, after setting all properties.
function avgLineScanEnd_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanSmooth_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanSmooth (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baselineStart_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baselineStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baselineEnd_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baselineEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseFrameStart_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseFrameStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseFrameEnd_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseFrameEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --------------------------------------------------------------------
function varargout = generic_Callback(h, eventdata, handles, varargin)
    % Stub for Callback of the uicontrol handles
    genericCallback(h);
% --- Executes during object creation, after setting all properties.
function analysisMode_CreateFcn(hObject, eventdata, handles)
% hObject    handle to analysisMode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanChannel_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanChannel (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseLineEnd_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseLineEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseLineStart_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseLineStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function numberOfROISlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numberOfROISlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanStartSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanStartSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanEndSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanEndSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function avgLineScanSmoothSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to avgLineScanSmoothSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseLineStartSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseLineStartSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseLineEndSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseLineEndSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseFrameStartSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseFrameStartSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function baseFrameEndSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to baseFrameEndSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function roiWidth_CreateFcn(hObject, eventdata, handles)
% hObject    handle to roiWidth (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function roiWidth_Callback(hObject, eventdata, handles)
% hObject    handle to roiWidth (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of roiWidth as text
%        str2double(get(hObject,'String')) returns contents of roiWidth as a double
% --- Executes during object creation, after setting all properties.
function roiWidthSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to roiWidthSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on slider movement.
function review_Callback(hObject, eventdata, handles)
    genericCallback(hObject);
    reviewFluorData;
% --- Executes during object creation, after setting all properties.
function epoch_CreateFcn(hObject, eventdata, handles)
% hObject    handle to epoch (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function epochSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to epochSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function review_CreateFcn(hObject, eventdata, handles)
% hObject    handle to review (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function reviewSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to reviewSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in selectROIButton.
function selectROIButton_Callback(hObject, eventdata, handles)
% hObject    handle to selectROIButton (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    set(hObject, 'Enable', 'off');
    try
        global state gh
        set(gh.fluorAnalysisSettings.selectROIButton, 'ForeGroundColor', [0 0 1]);
        setStatusString('Drag over ROI');
        siSelectionChannelToFront
        k = waitforbuttonpress;
        if isempty(findobj(gcf, 'Type', 'axes'))
            disp('*** NO axes***');
            set(hObject, 'Enable', 'on');
            set(gh.pcellControl.selectBoxButton, 'ForeGroundColor', [0 0 0]);
            return
        end
        point1 = get(gca,'CurrentPoint');    % button down detected
        finalRect = rbbox;                   % return figure units
        set(gh.fluorAnalysisSettings.selectROIButton, 'ForeGroundColor', [0 0 0]);
        setStatusString('');
        point2 = get(gca,'CurrentPoint');    % button up detected
        point1 = point1(1,1:2);              % extract x and y
        point2 = point2(1,1:2);
        p1 = min(point1,point2);             % calculate locations
        offset = abs(point1-point2);         % and dimensions
        x = [p1(1) p1(1)+offset(1) p1(1)+offset(1) p1(1) p1(1)];
        y = [p1(2) p1(2) p1(2)+offset(2) p1(2)+offset(2) p1(2)];
        x=round(x);
        y=round(y);
        hold on;
        axis manual;
        if size(state.analysis.roiDefs, 2)==2
            state.analysis.roiDefs(:,3:4)=0    ;
        end
        state.analysis.roiDefs(state.analysis.currentROINumber, :)=[x(1) x(2) y(1) y(3)];
    catch
        disp(['ROI selection error : ' lasterr]);
    end
    set(hObject, 'Enable', 'on');
% --- Executes during object creation, after setting all properties.
function currentROINumber_CreateFcn(hObject, eventdata, handles)
% hObject    handle to currentROINumber (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function currentROINumber_Callback(hObject, eventdata, handles)
% hObject    handle to currentROINumber (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of currentROINumber as text
%        str2double(get(hObject,'String')) returns contents of currentROINumber as a double
    genericCallback(hObject);
% --- Executes during object creation, after setting all properties.
function currentROINumberSlider_CreateFcn(hObject, eventdata, handles)
% hObject    handle to currentROINumberSlider (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background, change
%       'usewhitebg' to 0 to use default.  See ISPC and COMPUTER.
usewhitebg = 1;
if usewhitebg
    set(hObject,'BackgroundColor',[.9 .9 .9]);
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in rerunButton.
function rerunButton_Callback(hObject, eventdata, handles)
% hObject    handle to rerunButton (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    global state
    runFluorAnalysis(state.files.lastAcquisition);
% --- Executes during object creation, after setting all properties.
function peakStart_CreateFcn(hObject, eventdata, handles)
% hObject    handle to peakStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function peakStart_Callback(hObject, eventdata, handles)
% hObject    handle to peakStart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of peakStart as text
%        str2double(get(hObject,'String')) returns contents of peakStart as a double
% --- Executes during object creation, after setting all properties.
function peakEnd_CreateFcn(hObject, eventdata, handles)
% hObject    handle to peakEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
function peakEnd_Callback(hObject, eventdata, handles)
% hObject    handle to peakEnd (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of peakEnd as text
%        str2double(get(hObject,'String')) returns contents of peakEnd as a double
% --- Executes on button press in peakAverage.
function peakAverage_Callback(hObject, eventdata, handles)
% hObject    handle to peakAverage (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of peakAverage