Description of ROIScanName
Home > Imaging > FluoProcessing > ROIScanName.m
ROIScanName
PURPOSE
SYNOPSIS
function out=ROIScanName(channel, roi, acq)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
avginROIScans
plotROIBaselines
plotROIScans
plotROIScansMultiPanel
reviewFluorData
runFluorAnalysis
saveROIScans
runTraceAnalyzer
SOURCE CODE
function out=ROIScanName(channel, roi, acq)
    if nargin==2
        out=['c' num2str(channel) 'r' num2str(roi)];
    elseif nargin==3
        out=['c' num2str(channel) 'r' num2str(roi) '_' num2str(acq)];
    else
        out=[];
        error('ROISCanName: wrong nmber of inputs');
    end