Description of saveFluorAnalysisSettingsAs
Home > Imaging > FluoProcessing > saveFluorAnalysisSettingsAs.m
saveFluorAnalysisSettingsAs
PURPOSE
SYNOPSIS
function saveFluorAnalysisSettingsAs
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
saveFluorAnalysisSettings
setStatusString This function sets the status field in mainControls.
This function is called by:
saveFluorAnalysisSettings
SOURCE CODE
function saveFluorAnalysisSettingsAs
    global state
    if ~isempty(state.analysis.analysisSetupPath)
        try
            cd(state.analysis.analysisSetupPath)
        catch
        end
    end
    [fname, pname]=uiputfile('*.ana', 'Choose file for fluorescence analysis settings');
    if ~isnumeric(fname)
        periods=findstr(fname, '.');
        if any(periods)
            fname=fname(1:periods(1)-1);
        end
        state.analysis.analysisSetupFileName = fname;
        fname=[fname '.ana'];
        state.analysis.analysisSetupPath = pname;
        saveFluorAnalysisSettings;
    else
        setStatusString('Cannot open file');
    end